#!/bin/sh
set -eu

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

if ! git diff --cached --name-only --diff-filter=ACMR | rg -q '(^|/).*\.swift$|(^|/)\.swiftlint\.yml$'; then
  exit 0
fi

echo "Running swiftlint..."
"$repo_root/scripts/lint.sh"
