import Foundation
import XCTest

@testable import Alveary

final class ClaudeAdapterTests: XCTestCase {
    func testBuildArgsIncludesEachSupportedPermissionModeAndEffort() {
        let adapter = ClaudeAdapter()
        let permissionModes = DefaultProviderRegistry(agentRegistry: DefaultAgentRegistry())
            .provider(for: "claude")?
            .supportedPermissionModes?
            .map(\.value) ?? []

        XCTAssertFalse(permissionModes.isEmpty)

        for permissionMode in permissionModes {
            let args = adapter.buildArgs(
                config: AgentConfig(
                    providerId: "claude",
                    sessionId: "session-123",
                    workingDirectory: "/tmp/project",
                    permissionMode: permissionMode,
                    model: "sonnet",
                    effort: "max",
                    initialPrompt: nil
                )
            )

            XCTAssertTrue(args.containsSubsequence(["--permission-mode", permissionMode]))
            XCTAssertTrue(args.containsSubsequence(["--model", "sonnet"]))
            XCTAssertTrue(args.containsSubsequence(["--effort", "max"]))
        }
    }

    func testSessionLaunchUsesResumeAndForkWhenArtifactExists() throws {
        let adapter = ClaudeAdapter()
        let tempDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(at: tempDirectory, withIntermediateDirectories: true, attributes: nil)
        let sessionId = "session-123"
        let sessionFilePath = try XCTUnwrap(adapter.sessionFilePath(sessionId: sessionId, cwd: tempDirectory.path))
        let sessionFileURL = URL(fileURLWithPath: sessionFilePath)
        defer {
            try? FileManager.default.removeItem(at: sessionFileURL)
            try? FileManager.default.removeItem(at: sessionFileURL.deletingLastPathComponent())
        }
        try FileManager.default.createDirectory(
            at: sessionFileURL.deletingLastPathComponent(),
            withIntermediateDirectories: true,
            attributes: nil
        )
        try Data().write(to: sessionFileURL)

        let decision = adapter.sessionLaunch(
            sessionId: sessionId,
            cwd: tempDirectory.path,
            isResuming: true,
            forkSession: true
        )

        XCTAssertEqual(
            decision,
            SessionLaunchDecision(args: ["--resume", sessionId, "--fork-session"], continuity: .preserved)
        )
    }

    func testSessionLaunchFallsBackToFreshSessionWhenArtifactIsMissing() {
        let adapter = ClaudeAdapter()
        let tempDirectory = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)

        let decision = adapter.sessionLaunch(
            sessionId: "session-123",
            cwd: tempDirectory.path,
            isResuming: true,
            forkSession: true
        )

        XCTAssertEqual(
            decision,
            SessionLaunchDecision(args: ["--session-id", "session-123"], continuity: .restartedFresh)
        )
    }

    func testDecodePreservesParentToolUseIdAndToolMetadata() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "user",
            "parent_tool_use_id": "agent-tool-1",
            "message": [
                "role": "user",
                "content": [[
                    "type": "tool_result",
                    "tool_use_id": "tool-1",
                    "is_error": false,
                    "content": "stdout text"
                ]]
            ],
            "tool_use_result": [
                "stderr": "stderr text",
                "interrupted": true,
                "isImage": false,
                "noOutputExpected": true
            ]
        ]

        let events = adapter.decode(json)

        XCTAssertEqual(
            events,
            [
                .toolResult(
                    id: "tool-1",
                    output: "stdout text",
                    isError: false,
                    parentToolUseId: "agent-tool-1",
                    metadata: ToolResultMetadata(
                        stderr: "stderr text",
                        interrupted: true,
                        isImage: false,
                        noOutputExpected: true
                    )
                )
            ]
        )
    }

    func testDecodeUserTextEventProducesAssistantMessage() {
        let adapter = ClaudeAdapter()
        let caveat = [
            "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.",
            """
            DO NOT respond to these messages or otherwise consider them in your response
            unless the user explicitly asks you to.</local-command-caveat>
            """
        ].joined(separator: " ")
        let text = """
        \(caveat)
        Unknown command: /review-github-pr
        """
        let json: [String: Any] = [
            "type": "user",
            "message": [
                "role": "user",
                "content": [[
                    "type": "text",
                    "text": text
                ]]
            ]
        ]

        let events = adapter.decode(json)
        let expectedText = [
            (
                "Caveat: The messages below were generated by the user while running "
                + "local commands. DO NOT respond to these messages or otherwise "
                + "consider them in your response"
            ),
            "unless the user explicitly asks you to.",
            "Unknown command: /review-github-pr"
        ].joined(separator: "\n")

        XCTAssertEqual(
            events,
            [
                .message(
                    role: "assistant",
                    content: expectedText,
                    parentToolUseId: nil
                )
            ]
        )
    }

    func testDecodeUserTextEventSkipsWhitespaceOrWrapperOnlyMessage() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "user",
            "message": [
                "role": "user",
                "content": [[
                    "type": "text",
                    "text": " \n<local-command-caveat>\n</local-command-caveat>\n "
                ]]
            ]
        ]

        XCTAssertTrue(adapter.decode(json).isEmpty)
    }

    func testDecodeUserEventPreservesTextAndToolResultBlocks() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "user",
            "parent_tool_use_id": "agent-tool-1",
            "message": [
                "role": "user",
                "content": [
                    [
                        "type": "text",
                        "text": "Unknown command: /review-github-pr"
                    ],
                    [
                        "type": "tool_result",
                        "tool_use_id": "tool-1",
                        "is_error": true,
                        "content": "stdout text"
                    ]
                ]
            ],
            "tool_use_result": [
                "stderr": "stderr text",
                "interrupted": false,
                "isImage": false,
                "noOutputExpected": false
            ]
        ]

        let events = adapter.decode(json)

        XCTAssertEqual(
            events,
            [
                .message(
                    role: "assistant",
                    content: "Unknown command: /review-github-pr",
                    parentToolUseId: "agent-tool-1"
                ),
                .toolResult(
                    id: "tool-1",
                    output: "stdout text",
                    isError: true,
                    parentToolUseId: "agent-tool-1",
                    metadata: ToolResultMetadata(
                        stderr: "stderr text",
                        interrupted: false,
                        isImage: false,
                        noOutputExpected: false
                    )
                )
            ]
        )
    }

    func testDecodePlainUserTextEventBecomesAssistantMessage() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "user",
            "message": [
                "role": "user",
                "content": [[
                    "type": "text",
                    "text": "A plain echoed user message"
                ]]
            ]
        ]

        XCTAssertEqual(
            adapter.decode(json),
            [
                .message(
                    role: "assistant",
                    content: "A plain echoed user message",
                    parentToolUseId: nil
                )
            ]
        )
    }

    func testDecodeRequestInterruptedUserTextEventBecomesStopEvent() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "user",
            "message": [
                "role": "user",
                "content": [[
                    "type": "text",
                    "text": " [Request Interrupted by user] "
                ]]
            ]
        ]

        XCTAssertEqual(
            adapter.decode(json),
            [
                .stop(message: ConversationInterruption.displayMessage)
            ]
        )
    }

    func testDecodeRequestInterruptedForToolUseUserTextEventBecomesStopEvent() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "user",
            "message": [
                "role": "user",
                "content": [[
                    "type": "text",
                    "text": " [Request interrupted by user for tool use] "
                ]]
            ]
        ]

        XCTAssertEqual(
            adapter.decode(json),
            [
                .stop(message: ConversationInterruption.displayMessage)
            ]
        )
        XCTAssertTrue(
            ConversationInterruption.isRequestInterruptedByUserReason("[Request interrupted by user for tool use]")
        )
    }

    func testDecodeResultEventEmitsDeferredToolApproval() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "result",
            "session_id": "session-123",
            "stop_reason": "tool_deferred",
            "is_error": false,
            "usage": [
                "input_tokens": 10,
                "output_tokens": 2,
                "cache_read_input_tokens": 4
            ],
            "duration_ms": 42,
            "total_cost_usd": 0.01,
            "deferred_tool_use": [
                "id": "tool-1",
                "name": "Bash",
                "input": [
                    "command": "swift test"
                ]
            ]
        ]

        XCTAssertEqual(
            adapter.decode(json),
            [
                .toolApprovalRequested(
                    ToolApprovalRequest(
                        sessionId: "session-123",
                        toolUseId: "tool-1",
                        toolName: "Bash",
                        toolInput: "{\"command\":\"swift test\"}"
                    )
                ),
                .tokens(
                    input: 10,
                    output: 2,
                    cacheRead: 4,
                    isError: false,
                    stopReason: "tool_deferred",
                    durationMs: 42,
                    costUsd: 0.01,
                    permissionDenials: []
                )
            ]
        )
    }

    func testDecodeSystemInitEmitsPermissionModeChangedEventWhenPresent() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "system",
            "subtype": "init",
            "session_id": "session-123",
            "permissionMode": "plan"
        ]

        XCTAssertEqual(
            adapter.decode(json),
            [
                .sessionInit(sessionId: "session-123"),
                .permissionModeChanged("plan")
            ]
        )
    }

    func testDecodeSystemStatusEmitsPermissionModeChangedEventWhenPresent() {
        let adapter = ClaudeAdapter()
        let json: [String: Any] = [
            "type": "system",
            "subtype": "status",
            "permissionMode": "acceptEdits"
        ]

        XCTAssertEqual(
            adapter.decode(json),
            [
                .permissionModeChanged("acceptEdits")
            ]
        )
    }

    func testSendMessageWritesStructuredJSONLineToStdin() throws {
        let adapter = ClaudeAdapter()
        let process = Process()
        let pipe = Pipe()
        process.standardInput = pipe

        try adapter.sendMessage("hello world", to: process)
        pipe.fileHandleForWriting.closeFile()

        let payload = pipe.fileHandleForReading.readDataToEndOfFile()
        let payloadString = try XCTUnwrap(String(data: payload, encoding: .utf8))
        let trimmed = payloadString.trimmingCharacters(in: .whitespacesAndNewlines)
        let jsonData = try XCTUnwrap(trimmed.data(using: .utf8))
        let object = try XCTUnwrap(JSONSerialization.jsonObject(with: jsonData) as? [String: Any])
        let message = try XCTUnwrap(object["message"] as? [String: Any])
        let content = try XCTUnwrap(message["content"] as? [[String: Any]])

        XCTAssertEqual(object["type"] as? String, "user")
        XCTAssertEqual(message["role"] as? String, "user")
        XCTAssertEqual(content.first?["type"] as? String, "text")
        XCTAssertEqual(content.first?["text"] as? String, "hello world")
    }
}

private extension [String] {
    func containsSubsequence(_ subsequence: [String]) -> Bool {
        guard !subsequence.isEmpty, subsequence.count <= count else {
            return subsequence.isEmpty
        }

        for startIndex in 0...(count - subsequence.count)
        where Array(self[startIndex..<(startIndex + subsequence.count)]) == subsequence {
            return true
        }

        return false
    }
}
