import XCTest

@testable import Alveary

@MainActor
extension HostToolTranscriptCatalogTests {
    func testTheListingToolIsTheOneReadOnlyLookupWithACard() {
        XCTAssertNotNil(
            HostToolTranscriptCatalog.descriptor(forToolName: PullRequestHostToolCatalog.listToolName)
        )
        // Every other read-only lookup still renders as an ordinary tool row.
        for readOnly in [
            PullRequestHostToolCatalog.detailToolName,
            PullRequestHostToolCatalog.timelineToolName,
            PullRequestHostToolCatalog.diffToolName,
            ThreadHostToolCatalog.listPullRequestsToolName,
            ThreadHostToolCatalog.listThreadsToolName
        ] {
            XCTAssertNil(HostToolTranscriptCatalog.descriptor(forToolName: readOnly), readOnly)
        }
    }

    /// A read decides nothing, so the card carries no outcome marker and never waits on one.
    func testTheListingCardRecordsNoOutcome() throws {
        let descriptor = try XCTUnwrap(
            HostToolTranscriptCatalog.descriptor(forToolName: PullRequestHostToolCatalog.listToolName)
        )
        XCTAssertNil(descriptor.outcomeKey(Self.listOutput))
    }

    func testListRowsComeFromTheStructuredResult() throws {
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: Self.listOutput, isError: false)
        )

        XCTAssertEqual(content.status, .listed)
        XCTAssertEqual(content.filter, .reviewing)
        XCTAssertEqual(content.rows.map(\.identifier.displayKey), ["octo/alpha#7", "octo/beta#12"])
        XCTAssertEqual(content.rows.map(\.status), [.open, .draft])
        XCTAssertEqual(content.rows.first?.title, "Retry transient GitHub failures")
    }

    /// The result caps at 50 rows, so a larger match set has to say what it is not showing.
    func testATruncatedListReportsTheRowsItLeftOut() throws {
        let output = """
        {"filter":"all","pull_requests":[{"number":7,"repository":"octo/alpha","status":"open",\
        "title":"One"}],"total_count":4}
        """
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: output, isError: false)
        )

        XCTAssertEqual(content.hiddenRowCount, 3)
        let entry = HostToolWidgetEntry(
            id: "tool-1",
            toolName: PullRequestHostToolCatalog.listToolName,
            content: .pullRequestList(content),
            isComplete: true
        )
        XCTAssertEqual(HostToolWidgetSummary.detail(for: entry), "3 more not shown")
    }

    func testAnEmptyListStillRendersItsCard() throws {
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(
                input: Self.listInput,
                output: #"{"filter":"reviewing","pull_requests":[],"total_count":0}"#,
                isError: false
            )
        )

        XCTAssertEqual(content.rows, [])
        let entry = HostToolWidgetEntry(
            id: "tool-1",
            toolName: PullRequestHostToolCatalog.listToolName,
            content: .pullRequestList(content),
            isComplete: true
        )
        // The scope is what makes an empty answer meaningful — "none to review" is not "none".
        XCTAssertEqual(HostToolWidgetSummary.text(for: entry), "No pull requests to review")
    }

    /// Some providers persist only the tool's plain-text fallback, so the card has to read its
    /// rows out of that too — otherwise it lands with nothing to show.
    func testRowsAreReadFromThePlainTextFallback() throws {
        let output = """
        Found 3 pull requests (all). Some results were unavailable: Resource protected by SAML:
        - octo/alpha#7 Retry transient GitHub failures (open, by afollestad, +6/-1)
        - octo/beta#12 Add adaptive icon generated by Android Studio. (merged, by afollestad, +26/-0)
        - other/gamma#3046 Add request transformation example (closed, by afollestad, +53/-0)
        """
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: output, isError: false)
        )

        XCTAssertEqual(content.status, .listed)
        XCTAssertEqual(content.filter, .all)
        XCTAssertEqual(
            content.rows.map(\.identifier.displayKey),
            ["octo/alpha#7", "octo/beta#12", "other/gamma#3046"]
        )
        XCTAssertEqual(content.rows.map(\.status), [.open, .merged, .closed])
        // A title with its own punctuation keeps it; only the trailing metadata comes off.
        XCTAssertEqual(content.rows[1].title, "Add adaptive icon generated by Android Studio.")
        XCTAssertTrue(content.hasWarnings)
    }

    /// The fallback shapes belong to `PullRequestHostToolService+Listing.swift`. Parsing the real
    /// tool's own output keeps the two from drifting apart silently.
    func testTheFallbackParserMatchesTheToolsRealText() async throws {
        let fixture = try PullRequestHostToolFixture()
        fixture.pullRequests.listResult = .success(
            PullRequestListResult(
                summaries: [
                    makePullRequestSummary(number: 7, repo: "octo/alpha", title: "Retry transient failures"),
                    makePullRequestSummary(number: 12, repo: "octo/beta", title: "Split the coordinator")
                ],
                warnings: ["octo-corp is not SSO-authorized"]
            )
        )
        let result = await fixture.handle(PullRequestHostToolCatalog.listToolName)

        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: result.text, isError: false)
        )
        XCTAssertEqual(content.rows.map(\.identifier.displayKey), ["octo/alpha#7", "octo/beta#12"])
        XCTAssertEqual(content.totalCount, 2)
        XCTAssertTrue(content.hasWarnings)
    }

    /// The card reports what this call listed, so a paging cursor must change nothing it renders —
    /// in either half of the result.
    func testTheCardIgnoresThePagingCursorInBothRepresentations() throws {
        let structured = try XCTUnwrap(
            PullRequestListWidgetParsing.content(
                input: Self.listInput,
                output: """
                {"filter":"reviewing","next_cursor":"ZXhhbXBsZQ","pull_requests":[{"number":7,\
                "repository":"octo/alpha","status":"open","title":"Keep"}],"total_count":1}
                """,
                isError: false
            )
        )
        XCTAssertEqual(structured.rows.map(\.title), ["Keep"])
        XCTAssertEqual(structured.totalCount, 1)

        let fallback = try XCTUnwrap(
            PullRequestListWidgetParsing.content(
                input: Self.listInput,
                output: """
                Found 1 open pull request (reviewing):
                - octo/alpha#7 Keep (open, by afollestad, +6/-1)
                More results are available — call list_involved_prs again with cursor: ZXhhbXBsZQ
                """,
                isError: false
            )
        )
        // The trailing line is not a row, so it must not become one.
        XCTAssertEqual(fallback.rows.map(\.identifier.displayKey), ["octo/alpha#7"])
        XCTAssertEqual(fallback.totalCount, 1)
        XCTAssertEqual(fallback.filter, .reviewing)
    }

    /// A landed result whose shape we do not recognize still has to settle the card, because the
    /// grouper patches a widget only when its parser returns something.
    func testAnUnreadableResultStillLandsTheCard() throws {
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(
                input: Self.listInput,
                output: "Something entirely unexpected.",
                isError: false
            )
        )

        XCTAssertEqual(content.status, .listedWithoutRows)
        let entry = HostToolWidgetEntry(
            id: "tool-1",
            toolName: PullRequestHostToolCatalog.listToolName,
            content: .pullRequestList(content),
            isComplete: true
        )
        // Neutral copy: it must claim neither a count nor an empty result.
        XCTAssertEqual(HostToolWidgetSummary.text(for: entry), "Listed pull requests")
        // And it must not dump the whole result into the one-line detail slot.
        XCTAssertNil(HostToolWidgetSummary.detail(for: entry))
        XCTAssertTrue(entry.isSettledWithoutDecision)
    }

    func testARunningCallRendersBeforeItsResultArrives() throws {
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: nil, isError: false)
        )

        XCTAssertEqual(content.status, .running)
        XCTAssertEqual(content.filter, .reviewing)
    }

    /// Each row opens a different pull request, so the card itself must not be one button.
    func testTheCardIsInertBecauseItsRowsAreTheControls() throws {
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: Self.listOutput, isError: false)
        )
        let entry = HostToolWidgetEntry(
            id: "tool-1",
            toolName: PullRequestHostToolCatalog.listToolName,
            content: .pullRequestList(content),
            isComplete: true
        )

        XCTAssertNil(entry.openableTarget)
        XCTAssertTrue(entry.isSettledWithoutDecision)
    }

    /// A row Alveary cannot resolve to a pull request would be an inert line the user clicks at.
    func testRowsWithoutAResolvableIdentifierAreDropped() throws {
        let output = """
        {"filter":"all","pull_requests":[{"number":7,"repository":"octo/alpha","status":"open","title":"Keep"},\
        {"status":"open","title":"Drop"}],"total_count":2}
        """
        let content = try XCTUnwrap(
            PullRequestListWidgetParsing.content(input: Self.listInput, output: output, isError: false)
        )

        XCTAssertEqual(content.rows.map(\.title), ["Keep"])
    }

    static let listInput = #"{"filter":"reviewing"}"#
    static let listOutput = """
    {"filter":"reviewing","pull_requests":[{"number":7,"repository":"octo/alpha","status":"open",\
    "title":"Retry transient GitHub failures"},{"number":12,"repository":"octo/beta","status":"draft",\
    "title":"Split the scheduler coordinator"}],"total_count":2}
    """
}
